services:
  frontend:
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

  backend:
    command: npm run dev
    volumes:
      - ./backend:/app
      - /app/node_modules
